[package]
name = "day-2b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
test-case = {workspace = true}

[dependencies]
itertools = {workspace = true}

[lints]
workspace = true
