[package]
name = "day-10a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
rustc-hash = {workspace = true}
utilities = { workspace = true }

[lints]
workspace = true
