[package]
name = "day-4a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
rustc-hash = { workspace = true }
anyhow = { workspace = true }
utilities = { workspace = true }

[lints]
workspace = true
